---
title: "FAIR EU soil vocabularies: an overview of joint efforts from some EU Soil Mission projects"
subtitle: "EGU25 ESSI3.2: One decade of FAIR Principles: Data Reusability and Impact in Earth System Sciences"
author: Mickael Beaufils, Kathi Schleidt, Fenny van Egmond, Paul van Genuchten
date: 2025-04-30
format:
  revealjs: 
    theme: default
---


 
## Use Cases

- While publishing a dataset of a field campaign, indicate the properties observed, using which procedure
- Use common vocabularies for indicating the properties and procedures
- In data model metadata use the same terms to annotate the columns
- Observations are used to create property distribution maps, use the method and property vocabularies to indicate the source data for the map
 
## [FAIR considerations](https://doi.org/10.1371/journal.pcbi.1009041)

- Findable 
  - Register vocabulary in a vocab registry ([fairsharing.org](https://fairsharing.org))
  - Concepts and Lists should have persistent identifiers (DOI/W3ID)
- Accessible 
  - Open format (json/xml/ttl/csv)
- Interoperable 
  - SKOS ontology 
  - Linkage to same and similar terms (prevent duplication)
- Reusable 
  - Open License (CC-0, CC-by)
  - Human friendly browsing (vocbench, skosmos)

 
## Challenges

- We have standardisation insitutes (iso, gsp, iuss) but they are quite disconnected from FAIR practices
- Historically vocabularies were defined as a list with a version number, terms were referenced by the list version. These days terms are identified individually and can occur in multiple lists.
- The SKOS ontology is highly expressive but tools to work with it are not widely adopted

## Stakeholders

- Standardisation bodies (ISO11074:2025)
- Legal texts / EU Soil monitoring law (Gemet/Eurovoc)
- Academic community (IUSS / WRB)
- UN global community (Agrovoc, GSP, Glosolan) 

## Role of research projects

- Can setup initial version of a vocabulary
- Can **not** own a vocabulary, due to the temporary character and lack of authority
- Can proove effectiveness of new approaches
- Can set up and endorse strategy on vocabulary development/adoption

## Glossary alignment, a typical project startup activity

- Understand if terms are already listed in other vocabularies
- If so, adopt their definition, reference them as 'sameAs' or 'closeMatch'
- Consider to report back to the common vocabularies if there is not a full match, maybe a narrower term should be defined

## Current initiatives aiming to align efforts on vocabulary development

- ISLANDR
- Marvic
- Soilwise
- EJP Soil
