---
title: "LSC-Hub programme"
author: van Genuchten, P; van der Woude, T;
date: 2025-08-05
format:
  revealjs:
    incremental: true
    theme: default
    logo: https://lsc-hubs.org/images/logo-lsc-hubs.svg
    footer: LSC-hubs project; DeSiRa
---

# Tuesday
 
- 09:00 Opening Remarks Kennedy Were
- 09:30 Introduction to the LSC Hub Project Kennedy Were 
- 10:00 Goals of the Training & Topic Overview Paul Interactive via menti.com
- 11:00 Coffee Break
- 11:15 Components of an LSC Hub 
- 12:30 Lunch
- 14:00 Intro to GitHub and Docker 
- 16:00 Wrap-up & Q&A All
- 18:00 Close

# Wednesday

- 9:00 Content Management: Create, Modify & Version Control 
- 11:00 Metadata Management: Ingest, Harmonize & Search 
- 12:30 Lunch
- 14:00 MapServer OGC Services: What, Why & How 
- 16:00 Introduction to TerriaJS 
- 17:30 Close

# Thursday

- 09:00 Automating Maintenance with GitHub Actions & Docker Compose
- 11:00 QoS Monitoring & Reporting: Uptime, Security, Performance & Usage
- 12:30 Lunch
- 14:00 Backup, Restore & Security: SSL, Domains & Email Configuration
- 16:00 Building the LSC Hub Community: Feedback, Registration & Roadmap
- 17:30 Close

# Friday

- 09:00 Managing Releases: Test → Staging → Production 
- 11:00 Use-Case Development & Implementation 
- 12:30 Lunch
- 14:00 Data Publication: FAIR Principles & LSC Standards 
- 16:00 Workshop Evaluation & Next Steps All Feedback survey & action planning
- 17:00 Close